### ISSUE TITLE
As a sub-superuser/admin, I want to be able to review the submitted comments, and add/remove comments so that I can moderate comments.

### ISSUE THREAD

**Issue by KarmickLiu** [XeroDiscrimination/XeroDiscrimination#49]
Acceptance criteria:
There's a section for comments in the admin portal.
There's an add button, when clicked a comments information form will pop up for admins to add comments.
There's a delete button after each comments entry, when clicked the comments will get deleted from the database.

**Comment by shreyasn995** [comment]
Reviewed by Xero
