### ISSUE TITLE
As a sub-superuser/admin, I want to be able to review the submitted comments, and highlight/pin comments so that I can prioritise useful ones to the top.

### ISSUE THREAD

**Issue by KarmickLiu** [XeroDiscrimination/XeroDiscrimination#50]
Acceptance criteria:
Under the comments data section, there's a highlight button, when clicked, under the organisation page's comment section, the comment will be highlighted and placed at the top of other comments.

**Comment by shreyasn995** [comment]
Reviewed by Xero

**Comment by Olivia-long94** [comment]
Completed.
