### ISSUE TITLE
As a sub-superuser/admin, I want to be able to review the nominated orgs and moderate them so that I can add new orgs to the application database

### ISSUE THREAD

**Issue by KarmickLiu** [XeroDiscrimination/XeroDiscrimination#51]
Acceptance Criteria:
There's a section for nominated organisations in the admin portal, which is different from the section for organisations that already exist in the application database.
Each nominated organisation entry is clickable, when clicked the information of the organisation recommendation will pop up.
There's an accept button at the bottom of the form, when clicked, the organisation will be added to the database and the user who nominated the form will receive a notification. 
There's a reject button at the bottom of the form, when clicked, the organisation will not be added to the database the user who nominated the form will receive a notification.

**Comment by shreyasn995** [comment]
Reviewed by Xero

**Comment by Olivia-long94** [comment]
Completed.
